### ISSUE TITLE
Preloader not closing

### ISSUE THREAD

**Issue by 0Ani** [longpdo/neumorphism#3]
After refreshing the page a few times, the preloader stops closing. 
Sometimes it never loads the main page. 
Look into this issue. Its a good template

**Comment by longpdo** [comment]
Thanks for your feedback. I could replicate the bug you mentioned. The merge request should fix that. I tested it with Chrome, Safari and Firefox.

**Comment by 0Ani** [comment]
Thanks a lot. It works perfectly now.
