### ISSUE TITLE
Cannot change background color

### ISSUE THREAD

**Issue by Seerow0** [longpdo/neumorphism#37]
Hi, great theme. Very customizable , however I cannot seem to change the colors on the main.scss file. I commit the update and change the color values but nothing happens. Essentially, I am trying to change the color scheme of the site but am having trouble. Everything else works great except changes I make to main.scss. Line 17 "$bg-color: rgba(43, 45, 47, 1); " stays the same when I change the values(the following rgb lines as well). I would appreciate any help towards this issue.

**Comment by longpdo** [comment]
Hi, thanks for checking out this repo. Sorry, been kinda behind on checking up on my open source repositories.

It sounds like that you just edited the `main.scss` file - without running the dev server in the background. 
If you did all the setup steps, you also need to run `gulp` or `yarn dev` to start the dev server before changing any code. 

Then, any changes to `main.scss` will be compiled and minimized to `main.min.css` inside the assets folder.

**Comment by Seerow0** [comment]
### 
Hey,
I appreciate the reply and will go ahead and close the issue when I have the time to attempt the above instructions. Thanks for the assist. I still use it as my main website and I really love the simplicity for mobile and web viewing.
