### ISSUE TITLE
Project links are redirecting to the same page

### ISSUE THREAD

**Issue by govindtank** [longpdo/neumorphism#5]
Links under the project section for each project redirecting to same current page. because of defined 

Line #11 ` <a class="highlight-link" href="{{project.github}}" target="_blank" rel="noreferrer">`
 in **_includes/section-projects.html**

should be replaced to `
 <a class="highlight-link" href="{{project.demo}}" target="_blank" rel="noreferrer">
`
to successfully redirect to project link.

**Comment by longpdo** [comment]
Thanks for your feedback.

You are right. I just fixed this in b5ed7e7.
