### ISSUE TITLE
Where can I quickly change the colors of the background, text, and particles?

### ISSUE THREAD

**Issue by milosarsik** [longpdo/neumorphism#7]
Hello, I would like to know where I can quickly change the colors of the UI. Such as making the particles blue, the background a light grey/white color and the text grey with a blue hover color.

Like the theme in the below image. 

![image](https://user-images.githubusercontent.com/44819768/87478533-eeab0200-c5f7-11ea-87b9-e3d769da6601.png)

**Comment by longpdo** [comment]
Thanks for trying out my theme.

Changing the color of the particles is fairly easy. 
In assets/particles.json line 11, you can change the color.

Changing the rest like the background color, text color, button hover color would need some changes in _sass/main.scss. 
I will try to mimic the style of the image you provided, maybe I will add an option for a light theme later on.

**Comment by milosarsik** [comment]
Thank you so much for the help I've managed to make a couple of the changes I wanted. Last thing is the particle and skills color.  I found out which style sheets style each component through just inspect element. Thanks again!

Here is an example of how I styled it: 
![image](https://user-images.githubusercontent.com/44819768/87680308-4312c680-c74b-11ea-805f-36a68d15c1fd.png)

**Comment by milosarsik** [comment]
One more thing, where can i change the colors of the starting loading page, here. 
![image](https://user-images.githubusercontent.com/44819768/87684156-e960cb00-c74f-11ea-9ec5-1ddc9d4eff16.png)

**Comment by milosarsik** [comment]
Nevermind, I have figure it out, I will go ahead and close this issue. Thanks again!
