### ISSUE TITLE
Github Pages displaying differently from locally hosted page

### ISSUE THREAD

**Issue by logansgithub** [longpdo/neumorphism#9]
Hi, I really like this template but I'm having some trouble using github pages.

I was able to run and edit the locally hosted site just fine but when I upload the files to github , the github pages site looks like its missing some dependencies or something. There are no colors or images/logos - almost like it's ignoring the assets folder. However, the locally hosted site looks great. I was wondering if you knew why this might be.

You can see what my unchanged github page looks like here:
https://logansgithub.github.io/test/

Additionally, the security tab raises a few dependabot security alerts about the lock file dependency versions- do I need to worry about these? Could this be causing the issue? Even if I update the versions I still get the problem however.

**Comment by logansgithub** [comment]
Nevermind! I found the path issue. It was the same as a previously resolved issue

**Comment by longpdo** [comment]
Thanks for your notice. I fixed the security alerts for the dependencies.
